version: '3.8'

services:
  postgres-dev:
    image: postgres:16
    container_name: stockguard-dev-db
    environment:
      POSTGRES_DB: stockguard_dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5433:5432"
    volumes:
      - stockguard_dev_data:/var/lib/postgresql/data
    networks:
      - stockguard-network

  postgres-stage:
    image: postgres:16
    container_name: stockguard-stage-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ngxOnzCyA641mQKsHCrUJQ==
    ports:
      - "5434:5432"
    volumes:
      - stockguard_stage_data:/var/lib/postgresql/data
    networks:
      - stockguard-network

  postgres-prod:
    image: postgres:16
    container_name: stockguard-prod-db
    environment:
      POSTGRES_DB: stockguard_prod
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpass
    ports:
      - "5435:5432"
    volumes:
      - stockguard_prod_data:/var/lib/postgresql/data
    networks:
      - stockguard-network

  stockguard-app:
    build: .
    container_name: stockguard-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: stage
      DB_HOST: stockguard-stage
      DB_NAME: postgres
      DB_USER: root
      DB_PASSWORD: ngxOnzCyA641mQKsHCrUJQ==
      JWT_SECRET: "GRrlZ2fZYGaa7LTLQuL0RCTC/rPOUkj6gGZIMnHMEvsQizCNA5TVnEmVcjiXcdmWi8wJKnPfvB4IKIKfyY+Fhw=="
    depends_on:
      - postgres-stage
    networks:
      - stockguard-network

volumes:
  stockguard_dev_data:
  stockguard_stage_data:
  stockguard_prod_data:

networks:
  stockguard-network:
