spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stockguard
    username: stockuser
    password: stockpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/stockguard
      client:
        registration:
          keycloak:
            client-id: stockguard-app
            client-secret: <PUT-YOUR-CLIENT-SECRET-HERE>
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/stockguard

server:
  port: 8081
