spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/stockguard_prod
    username: produser
    password: prodpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
